version: '2'
services:
  app:
    build: .
    container_name: ourAppRunning
    ports:
     - 4000:3004
    networks:
     - myNetwork

  db:
    image: mongo
    container_name: ourDbRunning
    networks:
      - myNetwork
networks:
  myNetwork:
    driver: bridge
